### ISSUE TITLE
Float2 precision bug

### ISSUE THREAD

**Issue by bhansconnect** [mlochbaum/Singeli#1]
I think that float2 may have a bug. It seems to have inaccurate results earlier than it should. There is also a possibility this is just a printing issue. Essentially, I wrote a program with float2 and then with big nat and got different results. I am still very much a beginner so I wouldn't be surprised if something else is wrong.

[Float2 version in BQN Repl](https://mlochbaum.github.io/BQN/try.html#code=IyBIaWdoZXIgcHJlY2lzaW9uIGRvdWJsZSBmcm9tIHNlbmdhbGkKVG8gICDihpAg4ouI4p+cMApBZGQxMiDihpAge2HwnZWKYjoKICBzIOKGkCBhICsgYgogIGF24oaQIHMgLSBiduKGkCBzIC0gYQogIOKfqHMsICvCtGHigL9iLWF24oC/Ynbin6kKfQpBZGQg4oaQIHth8J2VimI6CiAgciDihpAgYSAr4peL4oqRIGIKICBzIOKGkCAoLXIpICvCtCDCrzHijL3ijL3ijZ8oYTzil4viipFiKSBi4oy94oq44oi+YQogIHIgQWRkMTIgcwp9Cl9yZXByIOKGkCB7IGxlbuKAv2IgX/CdlaM6IHtj4oaQMCDii4Qge/Cdlakr4oapY+KLhGPihqnijIrwnZWpw7di4ouEYnzwnZWpfcKo8J2VqX0gwrcrwrQgYnzijIriiJjDt+KfnGLijZ8o4oaVbGVuKcKoIH0KCgpuIOKGkCAxMDAKbSDihpAgMjAKQiDihpAgKOKKosK7y5zin5w8QWRkwrTiiJgoMeKKuOKGkykpCuKAok91dCAo4oioYCcwJ+KKuOKJoCniirgv4oi+wrQnMCcr4oy9IDI14oC/MTAgX3JlcHIgQWRkwrRC4o2fKG4tMSkgVG/CqDHiiL4obS0xKeKlijA=)

[BigNat version](https://mlochbaum.github.io/BQN/try.html#code=IyBQb3dlciBvZiAxMCB0byBtYWtlIHByaW50aW5nIGVhc2llcgpiYXNlIOKGkCDiipEgMTDii4Y3ICAjIExlc3MgdGhhbiBoYWxmIDLii4Y1MwoKX3doaWxlXyDihpAge/CdlL3ijZ/wnZS+4oiY8J2UvV/wnZWjX/CdlL7iiJjwnZS94o2f8J2UvvCdlal9CgpfZXh0ZW5kIOKGkCB7IPCdlagg8J2UveKXiygo8J2VqOKMiOKXi+KJoPCdlakp4oq44oaRKSDwnZWpIH0KCkNhcnJ5IOKGkCB7CiAgYyDihpAgMAogIHIg4oaQIHvwnZWpK+KGqWPii4Rj4oap4oyK8J2VqcO3YmFzZeKLhGJhc2V88J2VqX3CqCDwnZWpCiAgcuKAv2MKfQoKQWRkIOKGkCB7CiAgMOKKuDzil7biiqPigL/iiL7CtCBDYXJyeSDwnZWoICtfZXh0ZW5kIPCdlakKfQoKUmVwciDihpAgewogICjiiKhgJzAn4oq44omgKeKKuC/iiL7CtCjiiqMrPcOXJzAn4oq4LSnin5wnICco4oy9N+KKuOKGkeKImOKMvSnCqOKAolJlcHLCqOKMvfCdlakKfQoKbiDihpAgMTAwCm0g4oaQIDIwCkIg4oaQICjiiqLCu8uc4p+cPEFkZMK04oiYKDHiirjihpMpKQrigKJPdXQgUmVwciBBZGTCtELijZ8obi0xKSA8wqgx4oi+KG0tMSnipYow) Note: does not actually run on web repl, requires cbqn

Both of these just copied the needed functions from the related `.bqn` files.
The float2 version fails because it generally has slightly off answers that I believe should fit within it's range.
This code and test case comes from a rosalind problem where bignat passes, but float2 fails.

For the current code these are the outputs:
float2 - 3533689183352073**61**428
bignat - 353368918335207375428

2 digits are different here: 61 -> 75

The final value here has 69 binary digits and is the largest number generated, so I don't think there should be any precision loss with float2.

**Comment by mlochbaum** [comment]
The `_repr` function is only intended for power-of-two bases, where division is exact. Singeli is safe because it only uses the left operand `16‿16`. Comparing in octal I get the same results. To verify this, for your float2 script just replace `25‿10 _repr` with `25‿8 _repr`, and for bignat use the following definitions instead of yours.

```
base ← 8⋆7
Repr ← { (∨`'0'⊸≠)⊸/'0'+⌽∾8{ 𝕗|⌊∘÷⟜𝕗⍟(↕7)¨ }𝕩 }
```

I think the right approach to format a double-float in base 10 is to split it into three parts with less than say 12 digits each. So, pick a number around 1e¯12 times the total and use that as a modulus to get leading digits. Then multiply those digits by that power of 10 *as a double-float* and get a double-float remainder (I think you might also want to compare at this point to make sure your digits aren't off by one?). Do that two more times and then you should be able to construct the number. Sounds tricky, sticking with bignat is definitely simpler.

Appreciate the sanity check anyway, thanks for the report!

**Comment by bhansconnect** [comment]
Thanks for looking into this. The explanation makes a lot of sense. Sticking with big nat sounds good to me.
